name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Application
        run: make

      - name: Test Application
        run: make test  # If you have a test target in your Makefile

